vars:
  APP_ID:
    default: 557a3710
  BUNDLE_ID:
    default: com.revolutionprep.kronos.local
  CI_BUILD_NUMBER:
    default: 1
  CHANNEL_NAME:
    default: Local
  NAME:
    default: Kronos Local
  MAX_STORE:
    default: 2
  MIN_BACKGROUND_DURATION:
    default: 30
  STORE_RELEASE_VERSION:
    default: 1.0.0
  UPDATE_API:
    default: https://api.ionicjs.com
  UPDATE_METHOD:
    default: background

platforms:
  ios:
    targets:
      App:
        buildNumber: $CI_BUILD_NUMBER
        plist:
          - replace: true
            file: ios/GoogleService-Info.plist
            entries:
              - CLIENT_ID: $CLIENT_ID
              - REVERSED_CLIENT_ID: $REVERSED_CLIENT_ID
              - GOOGLE_APP_ID: $GOOGLE_APP_ID