vars:
  CI_BUILD_NUMBER:
    default: 1

platforms:
  ios:
    targets:
      App:
        buildNumber: $CI_BUILD_NUMBER
        plist:
          - replace: true
            file: GoogleService-Info.plist
            entries:
              - CLIENT_ID: $CLIENT_ID
              - REVERSED_CLIENT_ID: $REVERSED_CLIENT_ID
              - GOOGLE_APP_ID: $GOOGLE_APP_ID